# Generated by Django 5.2 on 2025-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_booking_fare_booking_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare_per_day',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
