# Generated by Django 5.2 on 2025-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_make_vehicle_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fare_per_day',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
