# Generated by Django 5.2 on 2025-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_booking_paid_booking_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
